package querys
import com.learn.drools.querys.Device

function boolean test(float status){
System.out.println("---"+status);
return  status<20;
}

query normalDevice
   // $device:Device(value<20)
  // $device:Device(test(value)) 不好用
      $device:Device(isOk()) // boolean类的返回并不好用

end

query byName(String na)
    $device:Device(name==na)
end


rule "transform"
  when
     $device:Device(!isTransform())
  then
    $device.setValue($device.getValue()/10);
    $device.setTransform(true);
    update($device)
    //drools.halt();
   end

rule "判断"
    when
     $device:Device(isTransform()&&value>20)
     then
     $device.setOk(false);
 end



rule "exists_rule_1"
    when
     Device()
     then
     System.out.println("exists_rule_1_触发");
 end


 rule "exists_rule_2"
     when
      exists Device()
      then
      System.out.println("exists_rule_2_触发");
 end


 rule "time_2"
      timer(0s 2s)
      when
      then

 end