spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.1.81:3306/Test?useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initialSize: 5
      minIdle: 5
      maxActive: 20
      filter:
        stat:
          log-slow-sql: true
      aop-patterns: com.learn.springboot.chapter10.service.*,com.learn.springboot.chapter10.dao.*
  thymeleaf:
    cache: false
 #Mybatis 指定映射文件地址 开启驼峰命名
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
server:
  servlet:
    session:
      timeout: 65