#配置文件下 只能配置一个 多个需要扩展
application:
  security:
    oauth:
      client[0]:
        registered-redirect-uri: http://example.com
        # 客户端 id
        client-id: client1
        # 客户端密钥
        client-secret: $2a$10$HtVNoM1uG0xigsKPtn5QZuU0B6aVC9w4i.XAZ1X/7x9M/OfcTQ7zi
        # 授权范围
        scope: all
        # token 有效期
        access-token-validity-seconds: 6000
        # 刷新 token 的有效期
        refresh-token-validity-seconds: 6000
        # 允许的授权类型
        grant-type: authorization_code,password,refresh_token
        # 可以访问的资源 id
        resource-ids: oauth2
      client[1]:
        registered-redirect-uri: http://example.com
        client-id: client2
        client-secret: $2a$10$HtVNoM1uG0xigsKPtn5QZuU0B6aVC9w4i.XAZ1X/7x9M/OfcTQ7zi
        scope: all
        access-token-validity-seconds: 6000
        refresh-token-validity-seconds: 6000
        grant-type: authorization_code,password,refresh_token
        resource-ids: oauth2



